version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run: echo "deploying to production server"

workflows:
  version: 2
  build_and_test_deploy:
    jobs:
      - build:
      - test:
        requires:
          - build
          - deploy
        filters:
          branches:
            only: main
          
  deploy:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run: echo "deploying to production server"

  test:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run: echo 'replace me with real tests!' && false

