version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run: echo "deploying to production server"

  deploy:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run: echo "deploying to production server"

  test:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run: |
          # Run your actual tests here
          npm install --production
          npm test

workflows:
  version: 2
  build_and_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
            - deploy
          filters:
            branches:
              only: main

