version: 2.1

  jobs:
  build:
  docker:
   - image: cimg/node:18.12.0
   steps:
   - checkout:
   - run: echo "deploying to production derver"
   
   workflows:
   build_and_test_deply:
    jobs:
    - build:
    - test: 
   reqiures:
    - build:
    - deploy:
   requires:
    -test:
     filters:
      branches:
       only:main
